{
    "name": "Student Consultancy Suite",
    "summary": "Meta module for the community-first student consultancy addon suite",
    "version": "18.0.1.0.0",
    "category": "Services",
    "author": "180 Degrees Consulting ESCP",
    "website": "https://github.com/180dc-escp/odoo-student-consultancy",
    "license": "LGPL-3",
    "depends": [
        "student_consultancy_core",
        "student_consultancy_cycles",
        "student_consultancy_contacts",
        "student_consultancy_hr",
        "student_consultancy_recruitment",
        "student_consultancy_projects",
        "student_consultancy_reviews",
        "student_consultancy_website",
    ],
    "installable": True,
    "application": True,
}
