{
    "name": "180DC Operating Model",
    "summary": "Membership lifecycle, seasons, reviews, and mailing governance",
    "version": "18.0.1.0.0",
    "category": "Operations",
    "license": "LGPL-3",
    "depends": [
        "authentik_oauth_member_bridge",
        "x_180dc_member_contract",
        "x_180dc_engagement",
        "x_180dc_crm_engagement_handoff",
        "hr_recruitment",
        "mass_mailing",
        "survey",
        "hr_recruitment_survey",
    ],
    "data": [
        "data/mailing_contact_ui_cleanup.xml",
        "data/security_baseline_cleanup.xml",
        "data/survey_default_user_cleanup.xml",
        "security/operating_groups.xml",
        "security/ir.model.access.csv",
        "security/review_security.xml",
        "data/rule_bootstrap_data.xml",
        "data/survey_definition_data.xml",
        "views/season_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_job_views.xml",
        "views/hr_applicant_views.xml",
        "views/engagement_views.xml",
        "views/operating_policy_views.xml",
        "views/recruitment_profile_views.xml",
        "views/role_group_rule_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_views.xml",
        "views/approval_rule_views.xml",
        "views/commitment_views.xml",
        "views/promotion_request_views.xml",
        "views/review_views.xml",
        "views/review_rule_views.xml",
        "views/reviewer_policy_views.xml",
        "views/survey_definition_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
