from odoo import SUPERUSER_ID, api


def post_init_hook(cr_or_env, registry=None):
    env = cr_or_env if hasattr(cr_or_env, "registry") else api.Environment(cr_or_env, SUPERUSER_ID, {})
    env["x_180dc.season"]._x_180dc_seed_from_existing_data()
    env["hr.contract"].search([])._x_180dc_backfill_membership_seasons()
    engagements = env["x_180dc.engagement"].search([])
    engagements._x_180dc_backfill_seasons()
    engagements._x_180dc_backfill_consulting_reviewers()
    env["hr.recruitment.stage"]._x_180dc_ensure_default_pipeline()
    env["survey.survey"]._x_180dc_ensure_default_surveys()
    env["x_180dc.review.template"]._x_180dc_ensure_default_templates()
    env["x_180dc.recruitment_profile"]._x_180dc_seed_default_profiles()
    env["hr.job"].search([])._x_180dc_seed_recruitment_profiles_on_jobs()
    env["hr.job"].search([])._x_180dc_ensure_job_surveys()
    env["x_180dc.operating_policy"]._x_180dc_ensure_default_policy()
    env["x_180dc.role_group_rule"]._x_180dc_seed_default_rules()
    env["x_180dc.review.rule"]._x_180dc_seed_default_rules()
    env["x_180dc.approval.scope"]._x_180dc_seed_default_scopes()
    env["x_180dc.promotion_approval_rule"]._x_180dc_seed_default_rules()
    env["x_180dc.consulting_reviewer_policy"]._x_180dc_seed_default_policies()
    env["res.partner"]._x_180dc_ensure_default_mailing_lists()
    env["hr.employee"].search([])._x_180dc_sync_membership_state()
    env["res.partner"].search([])._x_180dc_sync_mailing_contacts()
    env.cr.commit()
