{
    "name": "180DC Website Content",
    "summary": "Public website content controls for 180DC ESCP",
    "version": "18.0.1.0.0",
    "category": "Website",
    "license": "LGPL-3",
    "depends": ["x_180dc_operating_model"],
    "assets": {
        "web.assets_backend": [
            "x_180dc_website_content/static/src/js/website_dashboard_action.js",
            "x_180dc_website_content/static/src/scss/website_dashboard.scss",
            "x_180dc_website_content/static/src/xml/website_dashboard_action.xml",
        ],
    },
    "data": [
        "security/ir.model.access.csv",
        "data/website_kpi_definition_data.xml",
        "data/website_settings_data.xml",
        "data/ir_cron_data.xml",
        "views/engagement_views.xml",
        "views/hr_contract_views.xml",
        "views/hr_department_views.xml",
        "views/hr_employee_views.xml",
        "views/hr_job_views.xml",
        "views/res_partner_views.xml",
        "views/website_kpi_definition_views.xml",
        "views/website_settings_views.xml",
        "views/website_manager_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
