from . import admin_rule_mixin
from . import approval_rule
from . import commitment
from . import engagement
from . import hr_applicant
from . import hr_candidate
from . import hr_contract
from . import hr_employee
from . import hr_job
from . import hr_recruitment_stage
from . import operating_policy
from . import promotion_request
from . import recruitment_profile
from . import role_group_rule
from . import res_partner
from . import res_users
from . import review
from . import review_rule
from . import reviewer_policy
from . import season
from . import survey
from . import survey_definition
